spring.application.name=Base_Pilot
# SQL-Scripts beim Start ausführen
# spring.sql.init.mode=always

# Pfad zur Datei
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:schema.sql

# =====================
# DATENBANK CONFIG
# =====================





# =====================
# JPA / HIBERNATE CONFIG
# =====================
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
# Dialekt für SQL Server
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Auto DDL (create, update, validate, none)
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=update

# Show SQL Queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================
# OPTIONAL: Connection Test
# =====================
spring.datasource.test-on-borrow=true
spring.datasource.validation-query=SELECT 1